manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 2adaa00d1092e41ce11dfae46ce7d2a5bad97ead
      import: app/west.yml
  self:
    path: config
